package com.example.read0r.Models;

import com.j256.ormlite.field.DatabaseField;

public class ReadableBook {
	public ReadableBook() {

	}

	public ReadableBook(String fileAddress, String title, String author, int pages,
			String category, long positionPointer) {
		this.fileAddress = fileAddress;
		this.title = title;
		this.author = author;
		this.pages = pages;
		this.category = category;
		
		this.length = 0;
		
		this.positionPointer = positionPointer;
	}

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	public int id;
	
	@DatabaseField
	public String fileAddress;
	
	@DatabaseField
	public String title;
	
	@DatabaseField
	public String author;
	
	@DatabaseField
	public int pages;
	
	@DatabaseField
	public String category;
	
	@DatabaseField
	public int length;
	
	@DatabaseField
	public long positionPointer;
}
